<# Build-LitePacks.ps1 — assemble S1-Lite payload + CDN packs from the Windows game.
   Read-only on the game folder. Output goes to OutDir (default F:\svc-packs):
     payload-lite.zip   S1 Lite (boots to menu + versus with lite roster)
     chars-<Dir>.zip    one per fighter (backup/ excluded)
     stages-full.zip data-full.zip sound-full.zip
     packs.sha256       SHA-256 of every zip
   Lite select.def is generated by filtering [Characters]/[ExtraStages]
   to the lite roster (engine errors on missing chars, so never ship a
   full select.def with a lite chars/ dir). #>
param(
  [string]$GameRoot = "F:\Z E FOLDER\zzzzzzzzzzTEMPS\Sega VS Capcom S1",
  [string]$OutDir = "F:\svc-packs",
  [string[]]$LiteFighters = @("Ryu_a", "SonicA"),
  [string[]]$LiteStages = @("SVC_STADIUM", "TRAINING_1994")
)

$ErrorActionPreference = "Stop"
$stage = Join-Path $OutDir "_stage"
Remove-Item -LiteralPath $stage -Recurse -Force -ErrorAction SilentlyContinue
New-Item -ItemType Directory -Path $stage | Out-Null

function Copy-Tree($src, $dst) {
  New-Item -ItemType Directory -Path $dst -Force | Out-Null
  robocopy $src $dst /E /XD backup /NFL /NDL /NJH /NJS | Out-Null
  if ($LASTEXITCODE -ge 8) { throw "robocopy failed: $src" }
}

# --- system dirs (full, minus junk) ---
Copy-Tree (Join-Path $GameRoot "data") (Join-Path $stage "data")
Copy-Tree (Join-Path $GameRoot "font") (Join-Path $stage "font")
Copy-Tree (Join-Path $GameRoot "sound") (Join-Path $stage "sound")
Copy-Tree (Join-Path $GameRoot "video") (Join-Path $stage "video")
Copy-Tree (Join-Path $GameRoot "external") (Join-Path $stage "external")
New-Item -ItemType Directory -Path (Join-Path $stage "save") | Out-Null
Copy-Item -LiteralPath (Join-Path $GameRoot "save\config.ini") -Destination (Join-Path $stage "save\config.ini")
Set-Content -LiteralPath (Join-Path $stage "save\stats.json") -Value "{}" -NoNewline

# --- lite chars + stages ---
New-Item -ItemType Directory -Path (Join-Path $stage "chars") | Out-Null
foreach ($c in $LiteFighters) { Copy-Tree (Join-Path $GameRoot "chars\$c") (Join-Path $stage "chars\$c") }
New-Item -ItemType Directory -Path (Join-Path $stage "stages") | Out-Null
foreach ($s in $LiteStages) {
  Copy-Item -LiteralPath (Join-Path $GameRoot "stages\$s.def") -Destination (Join-Path $stage "stages")
  Get-ChildItem -LiteralPath (Join-Path $GameRoot "stages") -File |
    Where-Object { $_.BaseName -eq $s -and $_.Extension -ne ".def" } |
    Copy-Item -Destination (Join-Path $stage "stages")
}

# --- lite select.def: filter entries to the lite roster ---
$sel = Get-Content -LiteralPath (Join-Path $GameRoot "data\select.def")
$section = ""
$out = foreach ($line in $sel) {
  if ($line -match "^\[(.+)\]") { $section = $Matches[1] }
  if ($section -eq "Characters" -and $line -match "^\s*([^;,\s][^,]*?)\s*(,|$)" -and $line -notmatch "^\s*blank\s*$") {
    $entry = $Matches[1].Trim()
    if ($LiteFighters -notcontains $entry) { continue }
  }
  if ($section -eq "ExtraStages" -and $line -match "stages/([A-Za-z0-9_]+)\.def") {
    if ($LiteStages -notcontains $Matches[1]) { continue }
  }
  $line
}
Set-Content -LiteralPath (Join-Path $stage "data\select.def") -Value $out -Encoding UTF8

# --- zip lite payload ---
$liteZip = Join-Path $OutDir "payload-lite.zip"
Remove-Item -LiteralPath $liteZip -Force -ErrorAction SilentlyContinue
py -3 (Join-Path $PSScriptRoot "zip-packs.py") $stage $liteZip

# --- full CDN packs ---
foreach ($d in Get-ChildItem -LiteralPath (Join-Path $GameRoot "chars") -Directory) {
  $tmp = Join-Path $OutDir "_tmpchar"; Remove-Item -LiteralPath $tmp -Recurse -Force -ErrorAction SilentlyContinue
  Copy-Tree $d.FullName (Join-Path $tmp $d.Name)
  py -3 (Join-Path $PSScriptRoot "zip-packs.py") (Join-Path $tmp $d.Name) (Join-Path $OutDir "chars-$($d.Name).zip")
}
Remove-Item -LiteralPath (Join-Path $OutDir "_tmpchar") -Recurse -Force -ErrorAction SilentlyContinue
$tmpS = Join-Path $OutDir "_tmpstages"; Remove-Item -LiteralPath $tmpS -Recurse -Force -ErrorAction SilentlyContinue
Copy-Tree (Join-Path $GameRoot "stages") $tmpS
py -3 (Join-Path $PSScriptRoot "zip-packs.py") $tmpS (Join-Path $OutDir "stages-full.zip")
Remove-Item -LiteralPath $tmpS -Recurse -Force -ErrorAction SilentlyContinue
py -3 (Join-Path $PSScriptRoot "zip-packs.py") (Join-Path $GameRoot "data") (Join-Path $OutDir "data-full.zip")
py -3 (Join-Path $PSScriptRoot "zip-packs.py") (Join-Path $GameRoot "sound") (Join-Path $OutDir "sound-full.zip")

# --- hashes + summary ---
Get-ChildItem -LiteralPath $OutDir -Filter "*.zip" | Get-FileHash -Algorithm SHA256 |
  ForEach-Object { "$($_.Hash)  $($_.Path | Split-Path -Leaf)" } |
  Set-Content -LiteralPath (Join-Path $OutDir "packs.sha256")
Get-ChildItem -LiteralPath $OutDir -Filter "*.zip" | Sort-Object Length -Descending |
  Format-Table Name, @{N = "MB"; E = { [math]::Round($_.Length / 1MB, 1) } }
Remove-Item -LiteralPath $stage -Recurse -Force
